src/main/urls.py
from django.urls import path
from . import views
app_name = "main"

urlpatterns = [
    path('', views.index, name="index"),
]

src/menu/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
]

src/pizzamama/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('menu/', include('menu.urls')),
    path('', include('main.urls')),
    path('', include('menu.api_urls')),
]

src/main/models.py
from django.db import models

# Create your models here.

src/menu/models.py
from django.db import models


class Pizza(models.Model):
    name = models.CharField(max_length=200)
    ingredients = models.CharField(max_length=400)
    price = models.FloatField(default=0)
    vegetarian = models.BooleanField(default=False)

    def __str__(self):
        return self.name

src/main/views.py
# Create your views here.
from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.
def index(request):
    return render(request, 'main/index.html')

src/menu/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core import serializers
from .models import Pizza


# Create your views here.
def index(request):
    # pizzas = Pizza.objects.all()
    # pizzas_infos = [pizza.name +" : " + str(pizza.price) + "$" for pizza in pizzas]
    # pizzas_infos_str = ", ".join(pizzas_infos)
    # return HttpResponse(f"Pizzas : {pizzas_infos_str}")
    pizzas = Pizza.objects.all().order_by('price')
    return render(request, 'menu/index.html', {'pizzas': pizzas})

def api_get_pizza(request):
    pizzas = Pizza.objects.all()
    json = serializers.serialize("json", pizzas)
    return HttpResponse(json)

src/main/templates/main/index.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PizzaMama MainPage</title>
    <link rel="stylesheet" href="{% static 'main/style.css' %}">
</head>
<body>
    <div class="centered">
        <img src="{% static 'main/images/main_logo.png' %}">
        <a href="{% url 'menu:index' %}">Go to Menu</a>
    </div>
</body>
</html>

src/menu/templates/menu/index.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pizza Menu</title>
    <link rel="stylesheet" href="{% static 'menu/style.css' %}">
</head>
<body>
    <a href="{% url 'main:index' %}"><img id="small_logo" src="{% static 'menu/images/small_logo.png' %}"></a>
    <div class="menu_title">
        <h1>Pizzas</h1>
    </div>

    <div class="menu_list">
        {% for pizza in pizzas %}
        <div class="menu_list_item">
            <span class="menu_list_title">{{ pizza.name }}</span>
            <span class="menu_list_price">{{ pizza.price | floatformat:2}}$</span>
            <span class="menu_list_ingredients">{{ pizza.ingredients }}</span>
            {% if pizza.vegetarian == True %}
                <span class="vegetarian_badge">Vegetarian</span>
            {% endif %}
        </div>
        {% endfor %}
    </div>

</body>
</html>